SELECT ts.FIRST_NAME,sum(ta.SELLER_PRICE ) FROM  TBL_AUCTION   ta,TBL_USER  ts GROUP BY ta.SELLER_ID  having ta.SELLER_ID = ts.USER_ID ;

SELECT ts.FIRST_NAME,sum(ta.SELLER_PRICE)   FROM  TBL_AUCTION   ta,TBL_USER  ts  where ta.SELLER_USER_ID  = ts.USER_ID  GROUP BY ta.SELLER_USER_ID;

Select TA_A_U.FIRST_NAME,sum(TA_A_U.SELLER_PRICE) from (SELECT ts.FIRST_NAME,ta.SELLER_PRICE,ta.SELLER_USER_ID   FROM  TBL_AUCTION   ta,TBL_USER  ts  where ta.SELLER_USER_ID  = ts.USER_ID ) TA_A_U GROUP BY (TA_A_U.SELLER_USER_ID);